/// Flutter icons CustomIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcon
///      fonts:
///       - asset: fonts/CustomIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcon {
  CustomIcon._();

  static const _kFontFam = 'CustomIcon';
  static const _kFontPkg = null;

  static const IconData vane = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vane_2 = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData weathercock = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ball = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData world = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fortune_teller = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gauge = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
